// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJxWRE28oUIxAfVrn2aATjCdRnLT5-Vuw',
    appId: '1:861298417123:web:10ce8e710c18f9b563d4d6',
    messagingSenderId: '861298417123',
    projectId: 'lifelens-8a4ab',
    authDomain: 'lifelens-8a4ab.firebaseapp.com',
    storageBucket: 'lifelens-8a4ab.firebasestorage.app',
    measurementId: 'G-Y1ZJWQ828H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcQhYNCpMDzazdrm_3qRlIyNodzPdthA',
    appId: '1:861298417123:android:d6c868441a9af7f463d4d6',
    messagingSenderId: '861298417123',
    projectId: 'lifelens-8a4ab',
    storageBucket: 'lifelens-8a4ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMktmipDud5amks59uw6dEOnSMJa7J42U',
    appId: '1:861298417123:ios:faafefd678909eb563d4d6',
    messagingSenderId: '861298417123',
    projectId: 'lifelens-8a4ab',
    storageBucket: 'lifelens-8a4ab.firebasestorage.app',
    iosBundleId: 'com.example.lifelens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMktmipDud5amks59uw6dEOnSMJa7J42U',
    appId: '1:861298417123:ios:faafefd678909eb563d4d6',
    messagingSenderId: '861298417123',
    projectId: 'lifelens-8a4ab',
    storageBucket: 'lifelens-8a4ab.firebasestorage.app',
    iosBundleId: 'com.example.lifelens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJxWRE28oUIxAfVrn2aATjCdRnLT5-Vuw',
    appId: '1:861298417123:web:04384f4f35e49a9963d4d6',
    messagingSenderId: '861298417123',
    projectId: 'lifelens-8a4ab',
    authDomain: 'lifelens-8a4ab.firebaseapp.com',
    storageBucket: 'lifelens-8a4ab.firebasestorage.app',
    measurementId: 'G-FHZDWS9NWS',
  );
}
